# GET
# Busca Tracking do pedido
###

GET http://localhost:3000/ordersTracking
Content-Type: application/json
user: 2

# GET
# Busca tracking do pedido pelo ID
###

GET http://localhost:3000/ordersTracking/1
Content-Type: application/json
user: 2

# PUT
# atualizar tracking do pedido
###

PATCH http://localhost:3000/ordersTracking
Content-Type: application/json
user: 2

{
  "id": 2,
  "status": "FINISHED"
}


# Status {
#   'CREATED' = 'CREATED',
#   'IN_PREPARATION' = 'IN_PREPARATION',
#   'READY' = 'READY',
#   'FINISHED' = 'FINISHED',
#   'CANCELED' = 'CANCELED',
# }