version: '3.9'

services:
  pgsql:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'pgsql'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

  api:
    depends_on:
      - pgsql
    container_name: nestjs
    image: nestjs-dev
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_LOCAL_PORT
    environment:
      - DATABASE_URL=$DATABASE_URL
      - TOKEN_MERCADO_PAGO=$TOKEN_MERCADO_PAGO
      - USERID=$USERID
      - POSID=$POSID
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - orderSystem

volumes:
  db:
networks:
  orderSystem:
    driver: bridge
